name: GitHub Actions

on: [push]

jobs:
    check_lint_format:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18" # 必要に応じてNode.jsのバージョンを指定

            - name: Install dependencies
              run: npm install

            - name: Install biome globally
              run: npm install -g @biomejs/biome

            - name: Run biome check
              run: npx @biomejs/biome check --write ./
